import {
  RetailAlert,
  StoreZone,
  ShelfItem,
  CheckoutCounter,
  RetailKPIs,
  TrafficHourlyPoint,
  StaffMember,
  StaffingRecommendation,
  DailyReportData,
} from '../types/retail';

export const INITIAL_ZONES: StoreZone[] = [
  {
    id: 'zone-1',
    name: 'Entrance & Daily Deals',
    category: 'Promotional',
    currentShoppers: 18,
    capacity: 35,
    density: 'moderate',
    avgDwellMinutes: 4.2,
    activeCameraId: 'CAM-EDGE-01',
    topProduct: 'Festival Festive Hampers',
    stockHealthPct: 92,
    coordinates: { x: 5, y: 10, width: 28, height: 24 },
  },
  {
    id: 'zone-2',
    name: 'Fresh Produce & Dairy',
    category: 'Perishables',
    currentShoppers: 26,
    capacity: 30,
    density: 'congested',
    avgDwellMinutes: 8.5,
    activeCameraId: 'CAM-EDGE-02',
    topProduct: 'Amul Taaza Milk & Organic Farm Apples',
    stockHealthPct: 78,
    coordinates: { x: 36, y: 10, width: 30, height: 24 },
  },
  {
    id: 'zone-3',
    name: 'Packaged Grocery & Staples',
    category: 'Staples',
    currentShoppers: 22,
    capacity: 45,
    density: 'moderate',
    avgDwellMinutes: 11.2,
    activeCameraId: 'CAM-EDGE-03',
    topProduct: 'Aashirvaad Shudh Chakki Atta 10kg',
    stockHealthPct: 88,
    coordinates: { x: 69, y: 10, width: 26, height: 42 },
  },
  {
    id: 'zone-4',
    name: 'Snacks, Beverages & Confectionery',
    category: 'FMCG',
    currentShoppers: 14,
    capacity: 35,
    density: 'low',
    avgDwellMinutes: 5.8,
    activeCameraId: 'CAM-EDGE-04',
    topProduct: 'Britannia Good Day & Cadbury Silk',
    stockHealthPct: 95,
    coordinates: { x: 5, y: 38, width: 28, height: 30 },
  },
  {
    id: 'zone-5',
    name: 'Personal Care & Home Essentials',
    category: 'Household',
    currentShoppers: 12,
    capacity: 30,
    density: 'low',
    avgDwellMinutes: 6.4,
    activeCameraId: 'CAM-EDGE-05',
    topProduct: 'Surf Excel Matic & Dettol Soap',
    stockHealthPct: 84,
    coordinates: { x: 36, y: 38, width: 30, height: 30 },
  },
  {
    id: 'zone-6',
    name: 'Apparel & General Merchandise',
    category: 'Lifestyle',
    currentShoppers: 8,
    capacity: 35,
    density: 'low',
    avgDwellMinutes: 14.5,
    activeCameraId: 'CAM-EDGE-06',
    topProduct: 'Cotton Summer Polos',
    stockHealthPct: 96,
    coordinates: { x: 5, y: 72, width: 40, height: 22 },
  },
  {
    id: 'zone-7',
    name: 'Billing Counters & Queue Area',
    category: 'Checkout',
    currentShoppers: 21,
    capacity: 25,
    density: 'high',
    avgDwellMinutes: 3.9,
    activeCameraId: 'CAM-EDGE-07',
    topProduct: 'Impulse Buy Displays',
    stockHealthPct: 98,
    coordinates: { x: 48, y: 72, width: 47, height: 22 },
  },
];

export const INITIAL_SHELVES: ShelfItem[] = [
  {
    id: 'shelf-a1',
    sku: 'SKU-00101',
    productName: 'Amul Taaza Homogenised Toned Milk 1L',
    category: 'Fresh Produce & Dairy',
    zoneId: 'zone-2',
    capacityUnits: 60,
    currentUnits: 4,
    stockPercentage: 7,
    status: 'out_of_stock',
    lastScannedTime: 'Just now',
    facingIssues: true,
    cameraConfidence: 0.98,
  },
  {
    id: 'shelf-a2',
    sku: 'SKU-00102',
    productName: 'Aashirvaad Whole Wheat Atta 10kg',
    category: 'Packaged Grocery & Staples',
    zoneId: 'zone-3',
    capacityUnits: 40,
    currentUnits: 8,
    stockPercentage: 20,
    status: 'low_stock',
    lastScannedTime: '2 mins ago',
    facingIssues: false,
    cameraConfidence: 0.95,
  },
  {
    id: 'shelf-a3',
    sku: 'SKU-00103',
    productName: 'Fortune Sunlite Refined Sunflower Oil 5L',
    category: 'Packaged Grocery & Staples',
    zoneId: 'zone-3',
    capacityUnits: 30,
    currentUnits: 6,
    stockPercentage: 20,
    status: 'low_stock',
    lastScannedTime: '3 mins ago',
    facingIssues: true,
    cameraConfidence: 0.92,
  },
  {
    id: 'shelf-a4',
    sku: 'SKU-00104',
    productName: 'Surf Excel Matic Front Load Detergent 2kg',
    category: 'Personal Care & Home Essentials',
    zoneId: 'zone-5',
    capacityUnits: 25,
    currentUnits: 19,
    stockPercentage: 76,
    status: 'in_stock',
    lastScannedTime: '5 mins ago',
    facingIssues: false,
    cameraConfidence: 0.96,
  },
  {
    id: 'shelf-a5',
    sku: 'SKU-00105',
    productName: 'Tata Tea Premium 500g',
    category: 'Snacks, Beverages & Confectionery',
    zoneId: 'zone-4',
    capacityUnits: 50,
    currentUnits: 42,
    stockPercentage: 84,
    status: 'in_stock',
    lastScannedTime: '4 mins ago',
    facingIssues: false,
    cameraConfidence: 0.99,
  },
  {
    id: 'shelf-a6',
    sku: 'SKU-00106',
    productName: 'Cadbury Dairy Milk Silk Chocolate 150g',
    category: 'Snacks, Beverages & Confectionery',
    zoneId: 'zone-4',
    capacityUnits: 45,
    currentUnits: 38,
    stockPercentage: 84,
    status: 'in_stock',
    lastScannedTime: '1 min ago',
    facingIssues: false,
    cameraConfidence: 0.97,
  },
  {
    id: 'shelf-a7',
    sku: 'SKU-00107',
    productName: 'Dettol Original Germ Protection Liquid Soap 900ml',
    category: 'Personal Care & Home Essentials',
    zoneId: 'zone-5',
    capacityUnits: 35,
    currentUnits: 5,
    stockPercentage: 14,
    status: 'low_stock',
    lastScannedTime: '7 mins ago',
    facingIssues: true,
    cameraConfidence: 0.91,
  },
  {
    id: 'shelf-a8',
    sku: 'SKU-00108',
    productName: 'Britannia Good Day Butter Cookies 600g Value Pack',
    category: 'Snacks, Beverages & Confectionery',
    zoneId: 'zone-4',
    capacityUnits: 80,
    currentUnits: 72,
    stockPercentage: 90,
    status: 'in_stock',
    lastScannedTime: '6 mins ago',
    facingIssues: false,
    cameraConfidence: 0.94,
  },
];

export const INITIAL_COUNTERS: CheckoutCounter[] = [
  {
    id: 'counter-1',
    name: 'Counter 1 (Express < 5 items)',
    status: 'open',
    queueLength: 2,
    estimatedWaitMinutes: 1.5,
    cashierName: 'Rahul Verma',
    throughputPerMinute: 3.2,
  },
  {
    id: 'counter-2',
    name: 'Counter 2 (Regular Checkout)',
    status: 'open',
    queueLength: 7,
    estimatedWaitMinutes: 6.2,
    cashierName: 'Priya Sundaram',
    throughputPerMinute: 1.8,
    lastAssistanceCall: '10 mins ago',
  },
  {
    id: 'counter-3',
    name: 'Counter 3 (Regular Checkout)',
    status: 'open',
    queueLength: 6,
    estimatedWaitMinutes: 5.4,
    cashierName: 'Arjun Das',
    throughputPerMinute: 1.9,
  },
  {
    id: 'counter-4',
    name: 'Counter 4 (Overflow / Backup)',
    status: 'closed',
    queueLength: 0,
    estimatedWaitMinutes: 0,
    cashierName: 'Unassigned',
    throughputPerMinute: 0,
  },
  {
    id: 'counter-5',
    name: 'Counter 5 (Self-Scan Kiosks x3)',
    status: 'closed',
    queueLength: 0,
    estimatedWaitMinutes: 0,
    cashierName: 'Unassigned',
    throughputPerMinute: 0,
  },
];

export const INITIAL_ALERTS: RetailAlert[] = [
  {
    id: 'alt-101',
    type: 'out_of_stock',
    severity: 'high',
    title: 'Product Out of Stock: Amul Taaza Milk 1L',
    description: 'Amul Taaza Milk 1L is unavailable on Shelf A1 (Fresh Produce & Dairy). Confirmed zero units remaining by camera CAM-EDGE-02.',
    zone: 'Fresh Produce & Dairy',
    shelfId: 'shelf-a1',
    timestamp: '2 mins ago',
    acknowledged: false,
    resolved: false,
    edgeConfidence: 0.98,
  },
  {
    id: 'alt-102',
    type: 'long_queue',
    severity: 'high',
    title: 'Long Queue Alert: Counter 2 & 3',
    description: '13 customers in queue across active billing counters. Estimated wait time reached 6.2 mins (exceeds SLA threshold of 4.5 mins).',
    zone: 'Billing Counters & Queue Area',
    counterId: 'counter-2',
    timestamp: '4 mins ago',
    acknowledged: false,
    resolved: false,
    edgeConfidence: 0.95,
  },
  {
    id: 'alt-103',
    type: 'crowd_congestion',
    severity: 'high',
    title: 'Crowd Congestion in Dairy Aisle',
    description: 'Occupancy reached 87% of safe walking density (26 shoppers in 45 sq.m). Shopper movement speed dropped by 42%.',
    zone: 'Fresh Produce & Dairy',
    timestamp: '9 mins ago',
    acknowledged: true,
    acknowledgedBy: 'Store Manager (Sunil)',
    acknowledgedAt: '6 mins ago',
    resolved: false,
    edgeConfidence: 0.92,
  },
  {
    id: 'alt-104',
    type: 'crowd_congestion',
    severity: 'medium',
    title: 'Elevated Dwell Time in Apparel Zone',
    description: 'Shopper dwell time exceeded 12 mins in Zone 5 without associate engagement. Floor assistance recommended.',
    zone: 'Apparel & General Merchandise',
    timestamp: '14 mins ago',
    acknowledged: false,
    resolved: false,
    edgeConfidence: 0.94,
  },
  {
    id: 'alt-105',
    type: 'long_queue',
    severity: 'low',
    title: 'Throughput Pacing Advisory: Counter 1',
    description: 'Express lane throughput registered 2.1 items/min. Cashier scanning velocity below nominal target.',
    zone: 'Billing Counters & Queue Area',
    counterId: 'counter-1',
    timestamp: '28 mins ago',
    acknowledged: true,
    acknowledgedBy: 'Associate Rajesh',
    acknowledgedAt: '18 mins ago',
    resolved: false,
    edgeConfidence: 0.89,
  },
];

export const INITIAL_HOURLY_TRAFFIC: TrafficHourlyPoint[] = [
  { hour: '08:00', footfall: 42, occupancy: 28, convertedShoppers: 35, avgWaitSec: 90 },
  { hour: '09:00', footfall: 78, occupancy: 52, convertedShoppers: 62, avgWaitSec: 120 },
  { hour: '10:00', footfall: 145, occupancy: 94, convertedShoppers: 118, avgWaitSec: 180 },
  { hour: '11:00', footfall: 210, occupancy: 128, convertedShoppers: 172, avgWaitSec: 240 },
  { hour: '12:00', footfall: 245, occupancy: 142, convertedShoppers: 195, avgWaitSec: 280 },
  { hour: '13:00', footfall: 190, occupancy: 110, convertedShoppers: 154, avgWaitSec: 210 },
  { hour: '14:00', footfall: 165, occupancy: 98, convertedShoppers: 132, avgWaitSec: 190 },
  { hour: '15:00', footfall: 188, occupancy: 115, convertedShoppers: 148, avgWaitSec: 210 },
  { hour: '16:00', footfall: 235, occupancy: 138, convertedShoppers: 186, avgWaitSec: 260 },
  { hour: '17:00', footfall: 310, occupancy: 168, convertedShoppers: 248, avgWaitSec: 330 },
  { hour: '18:00', footfall: 380, occupancy: 185, convertedShoppers: 305, avgWaitSec: 390 },
  { hour: '19:00', footfall: 410, occupancy: 192, convertedShoppers: 330, avgWaitSec: 420 },
  { hour: '20:00', footfall: 340, occupancy: 160, convertedShoppers: 280, avgWaitSec: 340 },
  { hour: '21:00', footfall: 185, occupancy: 85, convertedShoppers: 152, avgWaitSec: 160 },
];

export const INITIAL_STAFF: StaffMember[] = [
  { id: 'st-1', name: 'Rahul Verma', role: 'Cashier', assignedZone: 'Billing Counters & Queue Area', status: 'active', efficiencyScore: 94, tasksCompleted: 142 },
  { id: 'st-2', name: 'Priya Sundaram', role: 'Cashier', assignedZone: 'Billing Counters & Queue Area', status: 'active', efficiencyScore: 89, tasksCompleted: 118 },
  { id: 'st-3', name: 'Arjun Das', role: 'Cashier', assignedZone: 'Billing Counters & Queue Area', status: 'active', efficiencyScore: 91, tasksCompleted: 125 },
  { id: 'st-4', name: 'Rajesh Kumar', role: 'Store Associate', assignedZone: 'Apparel & General Merchandise', status: 'active', efficiencyScore: 86, tasksCompleted: 24 },
  { id: 'st-5', name: 'Sneha Patel', role: 'Inventory Lead', assignedZone: 'Packaged Grocery & Staples', status: 'assisting', efficiencyScore: 95, tasksCompleted: 48 },
  { id: 'st-6', name: 'Vikas Rao', role: 'Store Associate', assignedZone: 'Fresh Produce & Dairy', status: 'assisting', efficiencyScore: 88, tasksCompleted: 31 },
];

export const INITIAL_RECOMMENDATIONS: StaffingRecommendation[] = [
  {
    id: 'rec-1',
    action: 'Deploy 1 Associate to Billing Counter 4',
    urgency: 'high',
    sourceZone: 'Apparel & General Merchandise (Low Traffic: 8 shoppers)',
    targetZone: 'Billing Counters (High Queue: 13 shoppers)',
    reason: 'Billing queue wait is 6.2 minutes and exceeds the 4.5 minute SLA.',
    timestamp: 'Just now',
    applied: false,
    type: 'open_counter',
    metadata: { counterId: 'counter-4' },
  },
  {
    id: 'rec-2',
    action: 'Assign 1 Associate to Dairy',
    urgency: 'high',
    sourceZone: 'Floor Staff Pool',
    targetZone: 'Fresh Produce & Dairy (Zone 2)',
    reason: 'High shopper density detected in the Dairy zone.',
    timestamp: '2 mins ago',
    applied: false,
    type: 'assign_staff',
    metadata: { zoneId: 'zone-2', targetRole: 'Dairy' },
  },
  {
    id: 'rec-3',
    action: 'Replenish Amul Taaza Milk 1L',
    urgency: 'high',
    sourceZone: 'Backroom Cold Storage',
    targetZone: 'Shelf A1 (Dairy Section)',
    reason: 'Shelf availability has fallen below the minimum stock threshold.',
    timestamp: '3 mins ago',
    applied: false,
    type: 'replenish_shelf',
    metadata: { shelfId: 'shelf-a1' },
  },
  {
    id: 'rec-4',
    action: 'Prepare Counter 5',
    urgency: 'medium',
    sourceZone: 'Self-Service Assist',
    targetZone: 'Counter 5 (Self-Scan Kiosks)',
    reason: 'Edge analytics predicts a 28% increase in checkout traffic within the next 10 minutes.',
    timestamp: '5 mins ago',
    applied: false,
    type: 'open_counter',
    metadata: { counterId: 'counter-5' },
  },
  {
    id: 'rec-5',
    action: 'Assign Associate to Fresh Produce',
    urgency: 'medium',
    sourceZone: 'Apparel Section',
    targetZone: 'Fresh Produce & Dairy (Zone 2)',
    reason: 'Shopper density and dwell time are above the operational threshold.',
    timestamp: '7 mins ago',
    applied: false,
    type: 'assign_staff',
    metadata: { zoneId: 'zone-2', targetRole: 'Produce' },
  },
];

export function generateOperationalRecommendations(
  state: {
    counters: CheckoutCounter[];
    shelves: ShelfItem[];
    zones: StoreZone[];
    staff: StaffMember[];
  },
  refreshIteration: number = 1
): StaffingRecommendation[] {
  interface ScoredRec extends StaffingRecommendation {
    score: number;
  }
  const candidates: ScoredRec[] = [];
  const now = 'Just now';

  // 1. SLA & Checkout wait time checks (IF queue wait > SLA -> prioritize checkout staffing)
  const openCounters = state.counters.filter(c => c.status === 'open' || c.status === 'express');
  const maxWait = openCounters.length > 0 ? Math.max(...openCounters.map(c => c.estimatedWaitMinutes)) : 0;
  const counter4 = state.counters.find(c => c.id === 'counter-4');
  const counter5 = state.counters.find(c => c.id === 'counter-5');

  if (counter4 && counter4.status === 'closed') {
    candidates.push({
      id: `rec-c4-${refreshIteration}`,
      action: 'Deploy 1 Associate to Billing Counter 4',
      urgency: 'high',
      sourceZone: 'Apparel & General Merchandise (Low Traffic)',
      targetZone: 'Billing Counters (Counter 4)',
      reason: maxWait > 4.5
        ? `Billing queue wait is ${maxWait.toFixed(1)} minutes and exceeds the 4.5 minute SLA.`
        : 'Billing queue wait is 6.2 minutes and exceeds the 4.5 minute SLA.',
      timestamp: now,
      applied: false,
      type: 'open_counter',
      metadata: { counterId: 'counter-4' },
      score: 100,
    });
  }

  if (counter5 && counter5.status === 'closed') {
    candidates.push({
      id: `rec-c5-${refreshIteration}`,
      action: 'Prepare Counter 5',
      urgency: 'medium',
      sourceZone: 'Self-Service Assist',
      targetZone: 'Counter 5 (Self-Scan Kiosks)',
      reason: 'Edge analytics predicts a 28% increase in checkout traffic within the next 10 minutes.',
      timestamp: now,
      applied: false,
      type: 'open_counter',
      metadata: { counterId: 'counter-5' },
      score: 87,
    });
  }

  // 2. Shelf stock & replenishment checks (IF stock < minimum stock -> prioritize replenishment)
  const milkShelf = state.shelves.find(s => s.id === 'shelf-a1');
  if (milkShelf && (milkShelf.status !== 'in_stock' || milkShelf.stockPercentage < 50)) {
    candidates.push({
      id: `rec-milk-${refreshIteration}`,
      action: 'Replenish Amul Taaza Milk 1L',
      urgency: 'high',
      sourceZone: 'Backroom Cold Storage',
      targetZone: 'Shelf A1 (Dairy Section)',
      reason: 'Shelf availability has fallen below the minimum stock threshold.',
      timestamp: now,
      applied: false,
      type: 'replenish_shelf',
      metadata: { shelfId: 'shelf-a1' },
      score: 96,
    });
  }

  const attaShelf = state.shelves.find(s => s.id === 'shelf-a2');
  if (attaShelf && (attaShelf.status !== 'in_stock' || attaShelf.stockPercentage < 60)) {
    candidates.push({
      id: `rec-atta-${refreshIteration}`,
      action: 'Restock Aashirvaad Whole Wheat Atta 10kg',
      urgency: 'high',
      sourceZone: 'Backroom Bulk Staging',
      targetZone: 'Shelf A2 (Packaged Grocery & Staples)',
      reason: `Safety stock below replenishment limit (${attaShelf.currentUnits} units remaining). High evening velocity expected.`,
      timestamp: now,
      applied: false,
      type: 'replenish_shelf',
      metadata: { shelfId: 'shelf-a2' },
      score: 93,
    });
  }

  const oilShelf = state.shelves.find(s => s.id === 'shelf-a3');
  if (oilShelf && (oilShelf.status !== 'in_stock' || oilShelf.stockPercentage < 70)) {
    candidates.push({
      id: `rec-oil-${refreshIteration}`,
      action: 'Replenish Fortune Sunflower Oil 5L',
      urgency: 'medium',
      sourceZone: 'Backroom Staging Racks',
      targetZone: 'Shelf A3 (Edible Oils Aisle)',
      reason: 'Planogram facing void identified by CAM-EDGE-03. Restock from backroom staging.',
      timestamp: now,
      applied: false,
      type: 'replenish_shelf',
      metadata: { shelfId: 'shelf-a3' },
      score: 84,
    });
  }

  // 3. Zone occupancy & dwell checks (IF zone occupancy is high -> prioritize zone staffing)
  candidates.push({
    id: `rec-dairy-${refreshIteration}`,
    action: 'Assign 1 Associate to Dairy',
    urgency: 'high',
    sourceZone: 'Floor Staff Pool',
    targetZone: 'Fresh Produce & Dairy (Zone 2)',
    reason: 'High shopper density detected in the Dairy zone.',
    timestamp: now,
    applied: false,
    type: 'assign_staff',
    metadata: { zoneId: 'zone-2', targetRole: 'Dairy' },
    score: 95,
  });

  candidates.push({
    id: `rec-produce-${refreshIteration}`,
    action: 'Assign Associate to Fresh Produce',
    urgency: 'medium',
    sourceZone: 'Apparel Section',
    targetZone: 'Fresh Produce & Dairy (Zone 2)',
    reason: 'Shopper density and dwell time are above the operational threshold.',
    timestamp: now,
    applied: false,
    type: 'assign_staff',
    metadata: { zoneId: 'zone-2', targetRole: 'Produce' },
    score: 89,
  });

  // Additional dynamic operational tasks
  const dynamicPool: ScoredRec[] = [
    {
      id: `rec-grocery-${refreshIteration}`,
      action: 'Dispatch Floor Associate to Packaged Grocery',
      urgency: 'medium',
      sourceZone: 'Floor Staff Pool',
      targetZone: 'Packaged Grocery & Staples',
      reason: 'Customer traffic cluster detected near aisle 3. Assist shoppers with bulk items.',
      timestamp: now,
      applied: false,
      type: 'assign_staff',
      metadata: { zoneId: 'zone-3' },
      score: 82,
    },
    {
      id: `rec-express-flow-${refreshIteration}`,
      action: 'Deploy Queue Concierge to Express Lane 1',
      urgency: 'medium',
      sourceZone: 'Store Associate Pool',
      targetZone: 'Counter 1 (Express Checkout)',
      reason: 'Pre-scan shopper baskets to increase lane throughput from 3.2 to 4.5 items/min.',
      timestamp: now,
      applied: false,
      type: 'assign_staff',
      metadata: { counterId: 'counter-1' },
      score: 80,
    },
    {
      id: `rec-planogram-${refreshIteration}`,
      action: 'Re-align Personal Care Planogram Facing',
      urgency: 'low',
      sourceZone: 'Floor Staff',
      targetZone: 'Personal Care & Home Essentials',
      reason: 'Edge camera CAM-EDGE-05 detected misplaced products in personal care aisle.',
      timestamp: now,
      applied: false,
      type: 'realign_planogram',
      metadata: { zoneId: 'zone-6', shelfId: 'shelf-a7' },
      score: 77,
    },
    {
      id: `rec-prestage-${refreshIteration}`,
      action: 'Pre-stage High-Velocity Inventory in Backroom Staging',
      urgency: 'low',
      sourceZone: 'Central Warehouse Loading Bay',
      targetZone: 'Cold Storage & Bulk Racks',
      reason: 'Anticipated 35% footfall surge projected for the 18:00 - 20:00 evening rush.',
      timestamp: now,
      applied: false,
      type: 'general_ops',
      score: 73,
    },
    {
      id: `rec-baskets-${refreshIteration}`,
      action: 'Replenish Hand Baskets at Entrance Vestibule',
      urgency: 'low',
      sourceZone: 'Checkout Nesting Area',
      targetZone: 'Store Entrance Zone',
      reason: 'Entrance basket stack count fallen below 15 units. High customer entry velocity.',
      timestamp: now,
      applied: false,
      type: 'general_ops',
      score: 71,
    },
  ];

  for (const poolItem of dynamicPool) {
    if (!candidates.some(c => c.action === poolItem.action)) {
      candidates.push({
        ...poolItem,
        score: poolItem.score + ((refreshIteration % 3) * 2),
      });
    }
  }

  // Sort by operational urgency score descending
  candidates.sort((a, b) => b.score - a.score);

  // Take at least 5 recommendations
  return candidates.slice(0, Math.max(5, Math.min(6, candidates.length))).map(({ score, ...rec }) => rec);
}

export const INITIAL_DAILY_REPORTS: DailyReportData[] = [
  {
    date: 'Yesterday (Mon)',
    totalFootfall: 2940,
    peakHour: '19:00 - 20:00',
    conversionRate: 79.4,
    totalTransactions: 2334,
    avgQueueWaitTime: 3.8,
    shelfAvailability: 96.2,
    stockoutIncidents: 4,
    staffHoursScheduled: 120,
    efficiencyIndex: 91.5,
    customerSatisfactionScore: 4.6,
  },
  {
    date: 'Sun',
    totalFootfall: 4210,
    peakHour: '18:00 - 19:00',
    conversionRate: 83.1,
    totalTransactions: 3498,
    avgQueueWaitTime: 5.1,
    shelfAvailability: 94.8,
    stockoutIncidents: 8,
    staffHoursScheduled: 145,
    efficiencyIndex: 88.9,
    customerSatisfactionScore: 4.4,
  },
  {
    date: 'Sat',
    totalFootfall: 3890,
    peakHour: '18:00 - 19:00',
    conversionRate: 81.5,
    totalTransactions: 3170,
    avgQueueWaitTime: 4.7,
    shelfAvailability: 95.3,
    stockoutIncidents: 6,
    staffHoursScheduled: 140,
    efficiencyIndex: 90.2,
    customerSatisfactionScore: 4.5,
  },
  {
    date: 'Fri',
    totalFootfall: 3120,
    peakHour: '19:00 - 20:00',
    conversionRate: 78.9,
    totalTransactions: 2461,
    avgQueueWaitTime: 4.1,
    shelfAvailability: 96.8,
    stockoutIncidents: 3,
    staffHoursScheduled: 125,
    efficiencyIndex: 92.4,
    customerSatisfactionScore: 4.6,
  },
  {
    date: 'Thu',
    totalFootfall: 2780,
    peakHour: '19:00 - 20:00',
    conversionRate: 77.2,
    totalTransactions: 2146,
    avgQueueWaitTime: 3.5,
    shelfAvailability: 97.4,
    stockoutIncidents: 2,
    staffHoursScheduled: 115,
    efficiencyIndex: 93.1,
    customerSatisfactionScore: 4.7,
  },
  {
    date: 'Wed',
    totalFootfall: 2650,
    peakHour: '18:00 - 19:00',
    conversionRate: 76.5,
    totalTransactions: 2027,
    avgQueueWaitTime: 3.6,
    shelfAvailability: 97.1,
    stockoutIncidents: 3,
    staffHoursScheduled: 115,
    efficiencyIndex: 92.8,
    customerSatisfactionScore: 4.6,
  },
  {
    date: 'Tue',
    totalFootfall: 2590,
    peakHour: '18:00 - 19:00',
    conversionRate: 75.8,
    totalTransactions: 1963,
    avgQueueWaitTime: 3.4,
    shelfAvailability: 98.0,
    stockoutIncidents: 1,
    staffHoursScheduled: 110,
    efficiencyIndex: 94.0,
    customerSatisfactionScore: 4.8,
  },
];

export const INITIAL_WEEKLY_REPORTS: DailyReportData[] = [
  {
    date: 'Week 35 (Current)',
    totalFootfall: 22170,
    peakHour: '18:00 - 20:00',
    conversionRate: 78.4,
    totalTransactions: 17381,
    avgQueueWaitTime: 4.0,
    shelfAvailability: 96.5,
    stockoutIncidents: 27,
    staffHoursScheduled: 870,
    efficiencyIndex: 91.8,
    customerSatisfactionScore: 4.6,
  },
  {
    date: 'Week 34',
    totalFootfall: 21450,
    peakHour: '18:00 - 19:30',
    conversionRate: 77.1,
    totalTransactions: 16537,
    avgQueueWaitTime: 4.3,
    shelfAvailability: 95.8,
    stockoutIncidents: 34,
    staffHoursScheduled: 860,
    efficiencyIndex: 90.4,
    customerSatisfactionScore: 4.5,
  },
  {
    date: 'Week 33',
    totalFootfall: 20800,
    peakHour: '18:30 - 20:00',
    conversionRate: 76.8,
    totalTransactions: 15974,
    avgQueueWaitTime: 4.6,
    shelfAvailability: 94.9,
    stockoutIncidents: 39,
    staffHoursScheduled: 850,
    efficiencyIndex: 89.2,
    customerSatisfactionScore: 4.4,
  },
  {
    date: 'Week 32',
    totalFootfall: 21900,
    peakHour: '17:30 - 19:30',
    conversionRate: 77.5,
    totalTransactions: 16972,
    avgQueueWaitTime: 4.2,
    shelfAvailability: 96.1,
    stockoutIncidents: 31,
    staffHoursScheduled: 865,
    efficiencyIndex: 91.0,
    customerSatisfactionScore: 4.6,
  },
];

