import React from 'react';
import {
  Bell,
  AlertTriangle,
  CheckCircle2,
  Clock,
  Zap,
  CheckCheck,
  RotateCcw,
} from 'lucide-react';
import { useRetail } from '../context/RetailContext';
import { AlertsTable } from '../components/AlertsTable';

export const AlertsPage: React.FC = () => {
  const { alerts, triggerDemoAlert, acknowledgeAlert } = useRetail();

  const totalCount = alerts.length;
  const activeAlerts = alerts.filter(a => !a.resolved);
  const criticalCount = activeAlerts.filter(a => a.severity === 'critical').length;
  const highCount = activeAlerts.filter(a => a.severity === 'high').length;
  const unacknowledgedCount = activeAlerts.filter(a => !a.acknowledged).length;

  const handleAcknowledgeAll = () => {
    activeAlerts.forEach(a => {
      if (!a.acknowledged) {
        acknowledgeAlert(a.id, 'Store Manager (Bulk)');
      }
    });
  };

  return (
    <div id="alerts-page" className="space-y-6 pb-12">
      {/* Alert Center Header */}
      <div className="bg-white p-5 rounded-xl border border-slate-200 shadow-sm flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-sm sm:text-base font-bold text-slate-800 uppercase tracking-tight">
              Autonomous Alert & Incident Center
            </h2>
            <span className="rounded-full bg-rose-100 px-2.5 py-0.5 text-xs font-bold text-rose-800 border border-rose-200">
              {activeAlerts.length} Active
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Real-time notifications generated by on-device computer vision models for stock-outs, long queues, and crowd bottlenecks.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          {unacknowledgedCount > 0 && (
            <button
              type="button"
              onClick={handleAcknowledgeAll}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-xs font-semibold shadow-xs transition-colors"
            >
              <CheckCheck className="h-3.5 w-3.5" />
              Acknowledge All ({unacknowledgedCount})
            </button>
          )}

          {/* Quick simulation buttons for hackathon presentation */}
          <div className="flex items-center gap-1.5 bg-blue-50/80 p-1 rounded-md border border-blue-200">
            <span className="text-[11px] font-bold text-blue-900 px-2 flex items-center gap-1">
              <Zap className="h-3 w-3 text-blue-600" /> Demo:
            </span>
            <button
              type="button"
              id="alerts-demo-stockout"
              onClick={() => triggerDemoAlert('stock')}
              className="px-2 py-1 bg-white hover:bg-rose-50 text-rose-700 rounded text-[11px] font-semibold border border-slate-200 shadow-2xs"
            >
              + Out of Stock
            </button>
            <button
              type="button"
              id="alerts-demo-lowstock"
              onClick={() => triggerDemoAlert('low_stock')}
              className="px-2 py-1 bg-white hover:bg-amber-50 text-amber-700 rounded text-[11px] font-semibold border border-slate-200 shadow-2xs"
            >
              + Low Stock
            </button>
            <button
              type="button"
              id="alerts-demo-queue"
              onClick={() => triggerDemoAlert('queue')}
              className="px-2 py-1 bg-white hover:bg-amber-50 text-amber-700 rounded text-[11px] font-semibold border border-slate-200 shadow-2xs"
            >
              + Long Queue
            </button>
            <button
              type="button"
              id="alerts-demo-crowd"
              onClick={() => triggerDemoAlert('crowd')}
              className="px-2 py-1 bg-white hover:bg-sky-50 text-blue-700 rounded text-[11px] font-semibold border border-slate-200 shadow-2xs"
            >
              + Congestion
            </button>
            <button
              type="button"
              id="alerts-demo-shelf"
              onClick={() => triggerDemoAlert('shelf_availability')}
              className="px-2 py-1 bg-white hover:bg-blue-50 text-blue-700 rounded text-[11px] font-semibold border border-slate-200 shadow-2xs"
            >
              + Shelf Void
            </button>
          </div>
        </div>
      </div>

      {/* Incident Metric Summary Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3.5">
        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-500 uppercase">Critical Action</span>
            <span className="w-2 h-2 rounded-full bg-rose-500 animate-ping" />
          </div>
          <p className="text-2xl sm:text-3xl font-bold text-rose-600 mt-2 font-mono">{criticalCount}</p>
          <p className="text-[11px] text-slate-400 mt-1">Direct impact on revenue/SLA</p>
        </div>

        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-500 uppercase">High Priority</span>
            <span className="w-2 h-2 rounded-full bg-amber-500" />
          </div>
          <p className="text-2xl sm:text-3xl font-bold text-amber-600 mt-2 font-mono">{highCount}</p>
          <p className="text-[11px] text-slate-400 mt-1">Queue & density thresholds</p>
        </div>

        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-500 uppercase">Pending Staff Ack</span>
            <Clock className="h-4 w-4 text-slate-400" />
          </div>
          <p className="text-2xl sm:text-3xl font-bold text-slate-900 mt-2 font-mono">{unacknowledgedCount}</p>
          <p className="text-[11px] text-slate-400 mt-1">Awaiting floor response</p>
        </div>

        <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-500 uppercase">Resolved Today</span>
            <CheckCircle2 className="h-4 w-4 text-emerald-500" />
          </div>
          <p className="text-2xl sm:text-3xl font-bold text-emerald-600 mt-2 font-mono">
            {totalCount - activeAlerts.length}
          </p>
          <p className="text-[11px] text-slate-400 mt-1">Closed autonomously or by staff</p>
        </div>
      </div>

      {/* Full Alerts Table with Search & Filtering */}
      <AlertsTable />
    </div>
  );
};
